# Generated by Django 5.2 on 2026-06-21 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_auction_user_alter_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 21, 11, 0, 47, 649346, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='bid',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 21, 11, 0, 47, 650108, tzinfo=datetime.timezone.utc)),
        ),
    ]
