# Generated by Django 5.2 on 2026-06-21 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auction_start_time_bid_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 21, 14, 14, 32, 256919, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 21, 14, 14, 32, 257688, tzinfo=datetime.timezone.utc)),
        ),
    ]
